// <auto-generated />
using Example.MVC.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.MVC.Data.Migrations
{
    [DbContext(typeof(ExampleMVCDbContext))]
    [Migration("20230125073121_mik-5")]
    partial class mik5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Example.MVC.Core.Entities.Bolumler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bolumlers");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Dersler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Derslers");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Notlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("DerslerId")
                        .HasColumnType("int");

                    b.Property<int>("FinalNotu")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<double>("Ortalama")
                        .HasColumnType("float");

                    b.Property<int>("VizeNotu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DerslerId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Notlars");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Ogrenciler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.ToTable("Ogrencilers");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Notlar", b =>
                {
                    b.HasOne("Example.MVC.Core.Entities.Dersler", "Dersler")
                        .WithMany("Notlars")
                        .HasForeignKey("DerslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Example.MVC.Core.Entities.Ogrenciler", "Ogrenci")
                        .WithMany("Notlars")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dersler");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Ogrenciler", b =>
                {
                    b.HasOne("Example.MVC.Core.Entities.Bolumler", "Bolum")
                        .WithMany("Ogrencilers")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Bolumler", b =>
                {
                    b.Navigation("Ogrencilers");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Dersler", b =>
                {
                    b.Navigation("Notlars");
                });

            modelBuilder.Entity("Example.MVC.Core.Entities.Ogrenciler", b =>
                {
                    b.Navigation("Notlars");
                });
#pragma warning restore 612, 618
        }
    }
}
